### PR TITLE
Move Copy Attack Modal Blocked Actions To Backend

### LINKED ISSUE #1207: Fuzz Testing Failure Detected (`5804164761373583`)
Fuzz Testing Failure Detected. Check with the folliwng command:
```sh
npm run test:fuzz -- debug 5804164761373583
```

**Traceback:**
```
AssertionError [ERR_ASSERTION]: Client picked a blocked attack to copy: primary
 at modalRequestAction (file:///home/runner/work/hc-tcg/hc-tcg/server/src/routines/turn-actions.ts:332:3)
 at handleSingleTurnAction (file:///home/runner/work/hc-tcg/hc-tcg/server/src/routines/game.ts:432:5)
 at turnActionsSaga (file:///home/runner/work/hc-tcg/hc-tcg/server/src/routines/game.ts:642:18)
 at turnActionsSaga.next (<anonymous>)
 at next (/home/runner/work/hc-tcg/hc-tcg/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1160:27)
 at currCb (/home/runner/work/hc-tcg/hc-tcg/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1254:7)
 at chCbAtKey (/home/runner/work/hc-tcg/hc-tcg/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:701:9)
 at Object.currCb [as cont] (/home/runner/work/hc-tcg/hc-tcg/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1254:7)
 at end (/home/runner/work/hc-tcg/hc-tcg/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1015:10)
 at Object.task.cont (/home/runner/work/hc-tcg/hc-tcg/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:839:11)
```

### PR DESCRIPTION
**Pull request by zunda-arrow**
This gives the Fuzz Tester access to the blocked actions which it did not have before. It also makes the turn action file no longer require checking the client's version of the modal.
I am not sure if this breaks Evilx or Evilx was always like this.

Closes #1207

### CODE REVIEW

File: common/models/game-model.ts [hunk 1]
```diff
@@ -342,6 +353,77 @@ export class GameModel {
...
+				query.effect.is(TimeSkipDisabledEffect),
+				query.effect.targetIsPlayerAnd(query.player.currentPlayer),
+			) &&
+			query.card.is(JoeHillsRare)(this, hermitCard)
+		)
+			blockedActions.push('SECONDARY_ATTACK')
+
+		const requestWithBlockedActions = {
+			...newRequest,
+			modal: {...modal, blockedActions: []},
```
Comment (Screaper91) [inline common/models/game-model.ts:422]:
```suggestion
			modal: {...modal, blockedActions: blockedActions},
```

**Comment by zunda-arrow** [comment]
After more consideration, I think setting blocked actions instead of the available options is backwards so I'm going to change it.

**Comment by zunda-arrow** [comment]
I have modified the code to work how I want it to

**Comment by zunda-arrow** [comment]
Thanks for fixing the unit tests! Was a bit busy today.
