### PR TITLE
Add clear cards confirm modal & fix typo

### LINKED ISSUE #1309: Typo in client statistics
In the client statistics line 1477 there is a typo.

Not doing it rn, will do it in a seperate pr once I've done game layout redesign.

### PR DESCRIPTION
**Pull request by Tyrannicodin**
Closes #1309

### CODE REVIEW

**Review by zunda-arrow — APPROVED** [review]
LGTM, (did not run)

File: client/src/app/deck/deck-edit.tsx [hunk 1]
```diff
@@ -486,7 +487,15 @@ function EditDeck({
 				onCancel={() => setShowUnsavedModal(!showUnsavedModal)}
 				onConfirm={back}
 			/>
-			<DeckLayout title={title} back={handleBack} returnText="Deck Editor">
+			<ConfirmModal
+				setOpen={showClearCardsModal}
+				title="Clear all cards"
+				description="Remove all cards?"
```
Comment (alicetouhou) [inline client/src/app/deck/deck-edit.tsx:493]:
```suggestion
				title="Remove all cards"
				description="Are you sure you want to remove all the cards in your deck?"
```
The current title is inconsistent with the button and the description is worded weirdly

**Comment by alicetouhou** [comment]
This is really minor, but I just realized it should be "Are you sure you want to remove all cards *from* your deck", not "in"
